#!/bin/bash

# Author: James Casbon, 2009

### BEGIN INIT INFO
# Provides:             galaxy
# Required-Start:       $network $local_fs $mysql
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Galaxy
### END INIT INFO

# Usage:
# 1. Modify the config variables
# 2. Copy this file to /etc/init.d/galaxy

. /lib/lsb/init-functions

#--- config

SERVICE_NAME="Galaxy"
ROOT="/home/galaxy"
RUN_AS="galaxy"
RUN_IN="$ROOT/dist"
PYENV="$ROOT/pyenv/bin"
DATE=`date +"%Y%m%d"`

#--- main actions

start() {
  echo "Starting $SERVICE_NAME... "
  cmd="cd $RUN_IN && . $PYENV/activate && sh run.sh --daemon --log-file $ROOT/log/${DATE}.log"
  case "$(id -un)" in
	$RUN_AS)
	  eval "$cmd"
	  ;;
	root)
	  su - $RUN_AS -c "$cmd"
	  ;;
	*)
	  echo "*** ERROR *** must be $RUN_AS or root in order to control this service" >&2
	  exit 1
  esac
  echo "...done."
}

stop() {
  echo -n "Stopping $SERVICE_NAME... "

  cmd="cd $RUN_IN && sh run.sh --stop-daemon"

  case "$(id -un)" in
	$RUN_AS)
	  eval "$cmd"
	  ;;
	root)
	  su - $RUN_AS -c "$cmd"
	  ;;
	*)
	  echo "*** ERROR *** must be $RUN_AS or root in order to control this service" >&2
	  exit 1
  esac

  echo "done."
}

status() {
  echo -n "$SERVICE_NAME status: "

  while read pid; do
	if [ "$(readlink -m /proc/$pid/cwd)" = "$(readlink -m $RUN_IN)" ]; then
	  echo "started"
	  return 0
	fi
  done < <(ps ax -o 'pid cmd' | grep -P '^\s*\d+ python ./scripts/paster.py serve' | awk '{print $1}')
  echo "stopped"
  return 3
}

notsupported() {
  echo "*** ERROR*** $SERVICE_NAME: operation [$1] not supported"
}

usage() {
  echo "Usage: $SERVICE_NAME start|stop|restart|status"
}


#---

case "$1" in
  start)
	start "$@"
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  status)
	set +e
	status
	exit $?
	;;
  '')
	usage >&2
	exit 1
	;;
  *)
	notsupported "$1" >&2
	usage >&2
	exit 1
	;;
esac
